spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
      console:
        settings:
          web-allow-others: true
        enabled: true
        path: /h2
  datasource:
      url: jdbc:h2:file:./account
      username: sa
      password:
      driverClassName: org.h2.Driver
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: false
          use_sql_comments: true
          format_sql: true
server:
  port: 8080
